import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { extractionSchema, ExtractionData } from '@/types/schemas'

const getOpenAIClient = () => {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('The OPENAI_API_KEY environment variable is missing or empty');
  }
  return new OpenAI({ apiKey });
}

const noteGenerationPrompt = `You are an expert allergist creating comprehensive medical documentation. Generate a complete allergy consultation note based on the extracted medical information.

CRITICAL REQUIREMENTS:
1. Create exactly 15 sections as specified below
2. Include "Needs Confirmation / Missing Data" and "Confidence Flags" sections
3. Never fabricate information - use clinical reasoning language when data is incomplete
4. Maintain strict medical documentation standards
5. Use appropriate medical terminology and allergist-specific language
6. Flag any OCR/transcription conflicts or uncertainties
7. NEVER include patient identifiers (names, DOB, addresses, etc.)

OUTPUT FORMAT:
Generate a structured note with these exact sections:

# Patient/Visit Information
- Date: [visit date or "Not specified"]
- Setting: [self/clinic/televisit or "Not specified"]
- Patient Alias: [alias or "Not provided"]

# Chief Complaint
[Primary reason for visit]

# History of Present Illness (HPI)
[Detailed HPI including onset, timeline, frequency, severity, triggers, relievers, exposures]

# Allergy History
## Food Allergies
[Structured list with allergen, reaction, severity, timing, certainty]

## Drug Allergies  
[Structured list with allergen, reaction, severity, timing, certainty]

## Environmental Allergies
[Structured list with allergen, reaction, seasonality, certainty]

## Stinging Insect Allergies
[Structured list with allergen, reaction, severity, certainty]

## Latex/Other Allergies
[Structured list with allergen, reaction, severity, certainty]

# Atopic Comorbidities
- Asthma: [yes/no/unknown]
- Eczema/Atopic Dermatitis: [yes/no/unknown]
- Chronic Rhinitis: [yes/no/unknown]
- Chronic Sinusitis: [yes/no/unknown]
- Urticaria/Angioedema: [yes/no/unknown]

# Testing & Labs Interpretation
## Allergy Testing
[Details of skin testing, specific IgE, component testing, challenges]

## Laboratory Studies
[Relevant lab results with interpretation]

## Other Studies
[Imaging, pulmonary function tests, etc.]

# Current Medications
[List with names, doses, frequencies, indications, responses, adverse effects]

# Review of Systems
**Positive:** [list positive findings]
**Negative:** [list negative findings]

# Physical Examination
[Relevant exam findings]

# Assessment
[Numbered list of problems/diagnoses with supporting evidence and confidence levels]

# Plan
[Numbered list of recommendations with rationale and priority levels]

# Structured Allergy List
[Comprehensive list of all identified allergens with reactions, severities, timing, and certainty levels]

# Patient Education
[Topics discussed with patient]

# Needs Confirmation / Missing Data
[Items requiring confirmation, incomplete information, or missing data]

# Source Quality Flags
[Quality indicators for source material - OCR confidence, transcription clarity, etc.]

---
**CONFIDENCE INDICATORS:**
- High confidence: Clear documentation from reliable sources
- Medium confidence: Reasonable certainty with some ambiguity
- Low confidence: Significant uncertainty or poor source quality

**CLINICAL REASONING NOTES:**
[Additional clinical reasoning not captured in structured format]

Generated by Allergy Scribe - AI-Assisted Documentation Tool
Visit ID: {visitId}
Generated: {current date/time}`

export async function POST(request: NextRequest) {
  try {
    const { visitId, extraction } = await request.json()

    if (!visitId || !extraction) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Validate the extraction data
    const validatedExtraction: ExtractionData = extractionSchema.parse(extraction)

    // Call OpenAI to generate the note
    const openai = getOpenAIClient()
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: noteGenerationPrompt
        },
        {
          role: 'user',
          content: `Generate a comprehensive allergy consultation note based on this extracted medical information:\n\n${JSON.stringify(validatedExtraction, null, 2)}\n\nEnsure all 15 required sections are included and maintain clinical accuracy.`
        }
      ],
      temperature: 0.2, // Low temperature for consistent, accurate output
      max_tokens: 6000
    })

    const generatedNote = completion.choices[0].message.content || ''

    // Post-process the note to ensure formatting
    const processedNote = generatedNote
      .replace(/\*\*\s*(.*?)\s*\*\*/g, '**$1**') // Ensure consistent bold formatting
      .replace(/#\s*(.*?)\s*$/gm, '# $1') // Ensure consistent header formatting
      .trim()

    return NextResponse.json({ note: processedNote })

  } catch (error) {
    console.error('Note generation error:', error)

    if (error instanceof Error && error.message.includes('API key')) {
      return NextResponse.json(
        { error: 'OpenAI API key not configured' },
        { status: 500 }
      )
    }

    if (error instanceof Error && error.message.includes('Validation')) {
      return NextResponse.json(
        { error: 'Failed to validate extraction data', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json(
      { error: 'Failed to generate medical note' },
      { status: 500 }
    )
  }
}