'use client'

import { useState, useEffect, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'

import { ArrowLeft, Copy, Download, FileText, RefreshCw } from 'lucide-react'
import { extractionSchema, ExtractionData } from '@/types/schemas'
import { jsPDF } from 'jspdf'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'

interface NoteModuleProps {
  visitId: string
  onBack: () => void
}

interface AllergenListItem {
  allergen: string
  reaction: string | null
  severity: string | null
  timing: string | null
  certainty: string
}

export function NoteModule({ visitId, onBack }: NoteModuleProps) {
  const [extraction, setExtraction] = useState<ExtractionData | null>(null)
  const [note, setNote] = useState<string>('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [isCopying, setIsCopying] = useState(false)

  // Simple toast function for notifications
  const toast = (message: string, type: 'success' | 'error' = 'success') => {
    alert(message) // Simple alert for now, can be replaced with proper toast later
  }

  const generateNote = useCallback(async (extractionData: ExtractionData) => {
    try {
      setIsGenerating(true)

      const response = await fetch('/api/generate-note', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          visitId,
          extraction: extractionData,
        }),
      })

      if (!response.ok) {
        throw new Error('Note generation failed')
      }

      const result = await response.json()
      setNote(result.note)

      toast('Your comprehensive allergy note has been generated.', 'success')

    } catch (error) {
      console.error('Note generation error:', error)
      toast('Failed to generate note. Please try again.', 'error')
    } finally {
      setIsGenerating(false)
    }
  }, [visitId])

  useEffect(() => {
    const extractionJson = sessionStorage.getItem(`extraction_${visitId}`)
    if (extractionJson) {
      const parsed = JSON.parse(extractionJson)
      setExtraction(parsed)
      generateNote(parsed)
    }
  }, [visitId, generateNote])

  const copyToClipboard = async () => {
    try {
      setIsCopying(true)
      await navigator.clipboard.writeText(note)
      toast('The note has been copied to your clipboard.', 'success')
    } catch (error) {
      console.error('Copy error:', error)
      toast('Failed to copy to clipboard.', 'error')
    } finally {
      setIsCopying(false)
    }
  }

  const downloadPDF = () => {
    try {
      const doc = new jsPDF()
      const pageHeight = doc.internal.pageSize.height
      const margin = 20
      let yPosition = margin

      const addText = (text: string, fontSize = 11, isBold = false) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage()
          yPosition = margin
        }

        doc.setFontSize(fontSize)
        if (isBold) {
          doc.setFont('helvetica', 'bold')
        } else {
          doc.setFont('helvetica', 'normal')
        }

        const lines = doc.splitTextToSize(text, doc.internal.pageSize.width - 2 * margin)
        doc.text(lines, margin, yPosition)
        yPosition += lines.length * fontSize * 0.4
      }

      // Title
      addText('ALLERGY CONSULTATION NOTE', 16, true)
      yPosition += 10

      // Add note content
      const lines = note.split('\n')
      lines.forEach(line => {
        if (line.trim()) {
          if (line.includes('**') && line.includes('**')) {
            // Handle bold text
            const boldText = line.replace(/\*\*/g, '')
            addText(boldText, 12, true)
          } else if (line.includes('#')) {
            // Handle headers
            const headerText = line.replace(/#/g, '').trim()
            addText(headerText, 14, true)
          } else {
            addText(line, 11, false)
          }
          yPosition += 5
        } else {
          yPosition += 3
        }
      })

      // Footer
      yPosition += 10
      addText(`\nGenerated by Allergy Scribe on ${new Date().toLocaleDateString()}`, 10, false)
      addText(`Visit ID: ${visitId}`, 10, false)

      doc.save(`allergy-note-${visitId}.pdf`)

      toast('The note has been downloaded as PDF.', 'success')

    } catch (error) {
      console.error('PDF download error:', error)
      toast('Failed to download PDF.', 'error')
    }
  }

  const downloadDOCX = () => {
    try {
      const sections: any[] = []

      // Title
      sections.push(
        new Paragraph({
          text: 'ALLERGY CONSULTATION NOTE',
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 }
        })
      )

      // Patient Information Header
      if (extraction?.patientAlias) {
        sections.push(
          new Paragraph({
            text: `Patient: ${extraction.patientAlias}`,
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 100 }
          })
        )
      }

      // Note content
      const lines = note.split('\n')
      lines.forEach(line => {
        if (line.trim()) {
          if (line.includes('#')) {
            // Headers
            const headerText = line.replace(/#/g, '').trim()
            sections.push(
              new Paragraph({
                text: headerText,
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
              })
            )
          } else if (line.includes('**') && line.includes('**')) {
            // Bold text
            const boldText = line.replace(/\*\*/g, '')
            sections.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: boldText,
                    bold: true,
                  })
                ],
                spacing: { after: 100 }
              })
            )
          } else {
            // Regular text
            sections.push(
              new Paragraph({
                text: line,
                spacing: { after: 50 }
              })
            )
          }
        }
      })

      // Add warnings if data is incomplete
      if (extraction?.needsConfirmation && extraction.needsConfirmation.length > 0) {
        sections.push(
          new Paragraph({
            text: '\n⚠️ ATTENTION: The following information requires confirmation:',
            spacing: { before: 300 }
          })
        )
        extraction.needsConfirmation.forEach(item => {
          sections.push(
            new Paragraph({
              text: `• ${item}`,
              spacing: { after: 50 }
            })
          )
        })
      }

      // Footer
      sections.push(
        new Paragraph({
          text: `\nGenerated by Allergy Scribe on ${new Date().toLocaleDateString()}`,
          spacing: { before: 200 }
        })
      )
      sections.push(
        new Paragraph({
          text: `Visit ID: ${visitId}`,
          spacing: { after: 100 }
        })
      )

      const doc = new Document({
        sections: [{
          children: sections
        }]
      })

      Packer.toBlob(doc).then(blob => {
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `allergy-note-${extraction?.patientAlias || visitId}.docx`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)

        toast('The medical note has been downloaded as Word document.', 'success')
      })

    } catch (error) {
      console.error('DOCX download error:', error)
      toast('Failed to download Word document.', 'error')
    }
  }

  const regenerateNote = () => {
    if (extraction) {
      generateNote(extraction)
    }
  }

  // Structured Allergy List rendering
  const renderStructuredAllergyList = () => {
    if (!extraction?.allergyHistory) return null

    // Convert different allergy types to a unified format
    const foodDrugAllergies = [
      ...(extraction.allergyHistory.food || []),
      ...(extraction.allergyHistory.drug || []),
      ...(extraction.allergyHistory.stingingInsects || []),
      ...(extraction.allergyHistory.latexOther || [])
    ].map(item => ({
      allergen: item.allergen,
      reaction: item.reaction,
      severity: item.severity,
      timing: (item as any).timing || null,
      certainty: item.certainty
    }))

    const environmentalAllergies = (extraction.allergyHistory.environmental || []).map(env => ({
      allergen: env.allergen,
      reaction: env.reaction,
      severity: null as string | null,
      timing: null as string | null,
      certainty: env.certainty
    }))

    const allAllergies: AllergenListItem[] = [
      ...foodDrugAllergies,
      ...environmentalAllergies
    ]

    if (allAllergies.length === 0) return null

    return (
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Structured Allergy List</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {allAllergies.map((allergy, index) => (
              <div key={index} className="border rounded-lg p-4">
                <div className="flex justify-between items-start mb-2">
                  <h4 className="font-medium text-gray-900">{allergy.allergen}</h4>
                  <Badge variant={allergy.certainty === 'confirmed' ? 'default' : 'secondary'}>
                    {allergy.certainty}
                  </Badge>
                </div>
                <div className="grid grid-cols-3 gap-4 text-sm">
                  <div>
                    <span className="font-medium">Reaction:</span>
                    <div className="text-gray-600">{allergy.reaction || 'Not specified'}</div>
                  </div>
                  <div>
                    <span className="font-medium">Severity:</span>
                    <div className="text-gray-600">{allergy.severity || 'Unknown'}</div>
                  </div>
                  <div>
                    <span className="font-medium">Timing:</span>
                    <div className="text-gray-600">{allergy.timing || 'Unknown'}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Step 3: Generated Allergy Note</CardTitle>
          <CardDescription>
            Review the comprehensive allergy note. You can copy to clipboard or download as PDF/DOCX.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {/* Action Buttons */}
          <div className="flex flex-wrap gap-2 mb-6">
            <Button onClick={copyToClipboard} disabled={isCopying} variant="outline">
              {isCopying ? (
                <>
                  <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                  Copying...
                </>
              ) : (
                <>
                  <Copy className="mr-2 h-4 w-4" />
                  Copy to Clipboard
                </>
              )}
            </Button>

            <Button onClick={downloadPDF} variant="outline">
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>

            <Button onClick={downloadDOCX} variant="outline">
              <FileText className="mr-2 h-4 w-4" />
              Download DOCX
            </Button>

            <Button onClick={regenerateNote} disabled={isGenerating} variant="outline">
              {isGenerating ? (
                <>
                  <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                  Regenerating...
                </>
              ) : (
                <>
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Regenerate Note
                </>
              )}
            </Button>
          </div>

          {/* Structured Allergy List */}
          {renderStructuredAllergyList()}

          {/* Generated Note */}
          {isGenerating ? (
            <div className="flex items-center justify-center h-64">
              <div className="text-center">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
                <p className="text-gray-600">Generating comprehensive allergy note...</p>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {/* Note Content */}
              <Card>
                <CardHeader>
                  <CardTitle>Clinical Note</CardTitle>
                </CardHeader>
                <CardContent>
                  <Textarea
                    value={note}
                    onChange={(e) => setNote(e.target.value)}
                    rows={20}
                    className="font-mono text-sm"
                  />
                </CardContent>
              </Card>

              {/* Needs Confirmation Section */}
              {extraction?.needsConfirmation && extraction.needsConfirmation.length > 0 && (
                <Card className="border-yellow-200 bg-yellow-50">
                  <CardHeader>
                    <CardTitle className="text-yellow-800">⚠️ Needs Confirmation / Missing Data</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="list-disc list-inside space-y-1">
                      {extraction.needsConfirmation.map((item, index) => (
                        <li key={index} className="text-yellow-700">{item}</li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Source Quality Flags */}
              {extraction?.sourceQualityFlags && extraction.sourceQualityFlags.length > 0 && (
                <Card className="border-orange-200 bg-orange-50">
                  <CardHeader>
                    <CardTitle className="text-orange-800">📊 Source Quality Flags</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="flex flex-wrap gap-2">
                      {extraction.sourceQualityFlags.map((flag, index) => (
                        <Badge key={index} variant="secondary" className="bg-orange-100 text-orange-800">
                          {flag}
                        </Badge>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Navigation */}
      <div className="flex justify-between">
        <Button onClick={onBack} variant="outline">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Review
        </Button>

        <div className="text-sm text-gray-500">
          Visit ID: {visitId}
        </div>
      </div>
    </div>
  )
}